# from https://github.com/tophf/mpiv/blob/master/.github/workflows/lint.yml
# and https://github.com/stefanoeb/eslint-action/blob/master/README.md

name: ESLint

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/**' # this yml is also excluded so you need to re-run it explicitly if necessary
      - .editorconfig
      - LICENSE
      - README.md
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/**' # this yml is also excluded so you need to re-run it explicitly if necessary
      - .editorconfig
      - LICENSE
      - README.md
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npx eslint . --ext .user.js
